name: HealthChecks InfluxDB Preview CD

on:
  push:
    tags:
      - preview-influxdb-*
      - preview-all-*
      
jobs:
  build:
    env:
      BUILD_CONFIG: Release
      VERSION_SUFFIX: -rc2.${{ github.run_number }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x
      - name: Restore
        run: dotnet restore ./src/HealthChecks.InfluxDB/HealthChecks.InfluxDB.csproj
      - name: Build
        run: dotnet build --no-restore ./src/HealthChecks.InfluxDB/HealthChecks.InfluxDB.csproj -c $BUILD_CONFIG
      - name: dotnet pack
        run: dotnet pack --no-build ./src/HealthChecks.InfluxDB/HealthChecks.InfluxDB.csproj --version-suffix $VERSION_SUFFIX -c $BUILD_CONFIG -o ./artifacts
      - name: Publish
        run: dotnet nuget push ./artifacts/AspNetCore.HealthChecks.InfluxDB.*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate


