name: HealthChecks OpenIdConnectServer CI

on:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.OpenIdConnectServer/**
      - test/HealthChecks.IdSvr.Tests/**
      - .github/workflows/healthchecks_idsvr_ci.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
  pull_request:
    branches: [ master ]
    paths:
    - src/HealthChecks.OpenIdConnectServer/**
    - test/HealthChecks.IdSvr.Tests/**
    - .github/workflows/healthchecks_idsvr_ci.yml
    - Directory.Build.props
    - Directory.Build.targets

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      idsvr:
        image: nakah/identityserver4
        ports:
          - 8888:80
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        include-prerelease: false
    - name: Restore dependencies
      run: dotnet restore ./src/HealthChecks.OpenIdConnectServer/HealthChecks.OpenIdConnectServer.csproj
    - name: Check formatting
      working-directory: ./src/HealthChecks.OpenIdConnectServer
      run: |
        dotnet format --no-restore --verify-no-changes --severity warn || (echo "Run 'dotnet format' to fix issues" && exit 1)
    - name: Build
      run: dotnet build --no-restore ./src/HealthChecks.OpenIdConnectServer/HealthChecks.OpenIdConnectServer.csproj
    - name: Test
      run: dotnet test ./test/HealthChecks.OpenIdConnectServer.Tests/HealthChecks.OpenIdConnectServer.Tests.csproj --verbosity normal
