name: HealthChecks CosmosDb CI

on:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.CosmosDb/**
      - test/HealthChecks.CosmosDb.Tests/**
      - .github/workflows/healthchecks_cosmosdb_ci.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
  pull_request:
    branches: [ master ]
    paths:
    - src/HealthChecks.CosmosDb/**
    - test/HealthChecks.CosmosDb.Tests/**
    - .github/workflows/healthchecks_cosmosdb_ci.yml
    - Directory.Build.props
    - Directory.Build.targets

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        include-prerelease: false
    - name: Restore dependencies
      run: dotnet restore ./src/HealthChecks.CosmosDb/HealthChecks.CosmosDb.csproj
    - name: Check formatting
      working-directory: ./src/HealthChecks.CosmosDb
      run: |
        dotnet format --no-restore --verify-no-changes --severity warn || (echo "Run 'dotnet format' to fix issues" && exit 1)
    - name: Build
      run: dotnet build --no-restore ./src/HealthChecks.CosmosDb/HealthChecks.CosmosDb.csproj
    - name: Test
      run: dotnet test ./test/HealthChecks.CosmosDb.Tests/HealthChecks.CosmosDb.Tests.csproj --verbosity normal
