name: HealthChecks ClickHouse DB CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.ClickHouse/**
      - test/HealthChecks.ClickHouse.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_clickhouse_ci.yml
      - Directory.Build.props
      - Directory.Build.targets
      - Directory.Packages.props
    tags-ignore:
      - release-*
      - preview-*

  pull_request:
    branches: [ master ]
    paths:
      - src/HealthChecks.ClickHouse/**
      - test/HealthChecks.ClickHouse.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_clickhouse_ci.yml
      - Directory.Build.props
      - Directory.Build.targets
      - Directory.Packages.props

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      clickhouse:
        image: clickhouse/clickhouse-server:24-alpine
        ports:
          - 8123:8123
        env:
          CLICKHOUSE_DB: default
          CLICKHOUSE_USER: default
          CLICKHOUSE_PASSWORD: "Password12!"
          CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x
      - name: Restore
        run: |
          dotnet restore ./src/HealthChecks.ClickHouse/HealthChecks.ClickHouse.csproj &&
          dotnet restore ./test/HealthChecks.ClickHouse.Tests/HealthChecks.ClickHouse.Tests.csproj
      - name: Check formatting
        run: |
          dotnet format --no-restore --verify-no-changes --severity warn ./src/HealthChecks.ClickHouse/HealthChecks.ClickHouse.csproj || (echo "Run 'dotnet format' to fix issues" && exit 1) &&
          dotnet format --no-restore --verify-no-changes --severity warn ./test/HealthChecks.ClickHouse.Tests/HealthChecks.ClickHouse.Tests.csproj || (echo "Run 'dotnet format' to fix issues" && exit 1)
      - name: Build
        run: |
          dotnet build --no-restore ./src/HealthChecks.ClickHouse/HealthChecks.ClickHouse.csproj &&
          dotnet build --no-restore ./test/HealthChecks.ClickHouse.Tests/HealthChecks.ClickHouse.Tests.csproj
      - name: Test
        run: >
          dotnet test
          ./test/HealthChecks.ClickHouse.Tests/HealthChecks.ClickHouse.Tests.csproj
          --no-restore
          --no-build
          --collect "XPlat Code Coverage"
          --results-directory .coverage
          --
          DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          flags: ClickHouse
          directory: .coverage
