name: HealthChecks Gcp.CloudFirestore CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.Gcp.CloudFirestore/**
      - test/HealthChecks.Gcp.CloudFirestore.Tests/**
      - .github/workflows/healthchecks_gcp_cloudfirestore_ci.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
  pull_request:
    branches: [ master ]
    paths:
    - src/HealthChecks.Gcp.CloudFirestore/**
    - test/HealthChecks.Gcp.CloudFirestore.Tests/**
    - .github/workflows/healthchecks_gcp_cloudfirestore_ci.yml
    - Directory.Build.props
    - Directory.Build.targets

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.0
      with:
        dotnet-version: 6.0.x
        include-prerelease: false
    - name: Restore
      run: |
        dotnet restore ./src/HealthChecks.Gcp.CloudFirestore/HealthChecks.Gcp.CloudFirestore.csproj &&
        dotnet restore ./test/HealthChecks.Gcp.CloudFirestore.Tests/HealthChecks.Gcp.CloudFirestore.Tests.csproj
    - name: Check formatting
      run: |
        dotnet format --no-restore --verify-no-changes --severity warn ./src/HealthChecks.Gcp.CloudFirestore/HealthChecks.Gcp.CloudFirestore.csproj || (echo "Run 'dotnet format' to fix issues" && exit 1) &&
        dotnet format --no-restore --verify-no-changes --severity warn ./test/HealthChecks.Gcp.CloudFirestore.Tests/HealthChecks.Gcp.CloudFirestore.Tests.csproj || (echo "Run 'dotnet format' to fix issues" && exit 1)
    - name: Build
      run: |
        dotnet build --no-restore ./src/HealthChecks.Gcp.CloudFirestore/HealthChecks.Gcp.CloudFirestore.csproj &&
        dotnet build --no-restore ./test/HealthChecks.Gcp.CloudFirestore.Tests/HealthChecks.Gcp.CloudFirestore.Tests.csproj
    - name: Test
      run: dotnet test --no-restore --no-build ./test/HealthChecks.Gcp.CloudFirestore.Tests/HealthChecks.Gcp.CloudFirestore.Tests.csproj
