name: HealthChecks InfluxDB CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.InfluxDB/**
      - test/HealthChecks.InfluxDB.Tests/**
      - .github/workflows/healthchecks_influxdb_ci.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
      - preview-*
      
  pull_request:
    branches: [ master ]
    paths:
      - src/HealthChecks.InfluxDB/**
      - test/HealthChecks.InfluxDB.Tests/**
      - .github/workflows/healthchecks_influxdb_ci.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x
      - name: Restore
        run: dotnet restore ./src/HealthChecks.InfluxDB/HealthChecks.InfluxDB.csproj &&
               dotnet restore ./test/HealthChecks.InfluxDB.Tests/HealthChecks.InfluxDB.Tests.csproj
      - name: Check formatting
        working-directory:
        run: |
          dotnet format --no-restore --verify-no-changes --severity warn ./src/HealthChecks.InfluxDB/HealthChecks.InfluxDB.csproj || (echo "Run 'dotnet format' to fix whitespace issues" && exit 1) &&
          dotnet format --no-restore --verify-no-changes --severity warn ./test/HealthChecks.InfluxDB.Tests/HealthChecks.InfluxDB.Tests.csproj || (echo "Run 'dotnet format' to fix analyzers issues" && exit 1)
      - name: Build
        run: |
          dotnet build --no-restore ./src/HealthChecks.InfluxDB/HealthChecks.InfluxDB.csproj &&
          dotnet build --no-restore ./test/HealthChecks.InfluxDB.Tests/HealthChecks.InfluxDB.Tests.csproj
      - name: Setup InfluxDB
        uses: influxdata/influxdb-action@v3
        with:
          influxdb_version: latest
          influxdb_org: influxdata
          influxdb_user: ci_user
          influxdb_password: password
          influxdb_bucket: dummy
      - name: Test
        run: dotnet test --no-restore --no-build ./test/HealthChecks.InfluxDB.Tests/HealthChecks.InfluxDB.Tests.csproj
