name: HealthChecks RabbitMQ CI

on:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.Rabbitmq/**
      - test/HealthChecks.RabbitMQ.Tests/**
      - .github/workflows/healthchecks_rabbitmq_ci.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
  pull_request:
    branches: [ master ]
    paths:
    - src/HealthChecks.Rabbitmq/**
    - test/HealthChecks.RabbitMQ.Tests/**
    - .github/workflows/healthchecks_rabbitmq_ci.yml
    - Directory.Build.props
    - Directory.Build.targets

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq
        ports:
          - 5672:5672
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.102
        include-prerelease: false
    - name: Restore
      run: |
        dotnet restore ./src/HealthChecks.Rabbitmq/HealthChecks.Rabbitmq.csproj &&
        dotnet restore ./test/HealthChecks.RabbitMQ.Tests/HealthChecks.RabbitMQ.Tests.csproj
    - name: Check formatting
      run: |
        dotnet format --no-restore --verify-no-changes --severity warn ./src/HealthChecks.Rabbitmq/HealthChecks.Rabbitmq.csproj || (echo "Run 'dotnet format' to fix issues" && exit 1) &&
        dotnet format --no-restore --verify-no-changes --severity warn ./test/HealthChecks.RabbitMQ.Tests/HealthChecks.RabbitMQ.Tests.csproj || (echo "Run 'dotnet format' to fix issues" && exit 1)
    - name: Build
      run: |
        dotnet build --no-restore ./src/HealthChecks.Rabbitmq/HealthChecks.Rabbitmq.csproj &&
        dotnet build --no-restore ./test/HealthChecks.RabbitMQ.Tests/HealthChecks.RabbitMQ.Tests.csproj
    - name: Test
      run: dotnet test --no-restore --no-build ./test/HealthChecks.RabbitMQ.Tests/HealthChecks.RabbitMQ.Tests.csproj
