name: HealthChecks Nats CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.Nats/**
      - test/HealthChecks.Nats.Tests/**
      - .github/workflows/healthchecks_nats_ci.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
  pull_request:
    branches: [ master ]
    paths:
    - src/HealthChecks.Nats/**
    - test/HealthChecks.Nats.Tests/**
    - .github/workflows/healthchecks_nats_ci.yml
    - Directory.Build.props
    - Directory.Build.targets

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      nats:
        image: nats:latest
        ports:
        - "4222:4222"
        - "8222:8222"
        - "6222:6222"
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.0
      with:
        dotnet-version: 6.0.x
        include-prerelease: false
    - name: Restore
      run: |
        dotnet restore ./src/HealthChecks.Nats/HealthChecks.Nats.csproj &&
        dotnet restore ./test/HealthChecks.Nats.Tests/HealthChecks.Nats.Tests.csproj
    - name: Check formatting
      run: |
        dotnet format --no-restore --verify-no-changes --severity warn ./src/HealthChecks.Nats/HealthChecks.Nats.csproj || (echo "Run 'dotnet format' to fix issues" && exit 1) &&
        dotnet format --no-restore --verify-no-changes --severity warn ./test/HealthChecks.Nats.Tests/HealthChecks.Nats.Tests.csproj || (echo "Run 'dotnet format' to fix issues" && exit 1)
    - name: Build
      run: |
        dotnet build --no-restore ./src/HealthChecks.Nats/HealthChecks.Nats.csproj &&
        dotnet build --no-restore ./test/HealthChecks.Nats.Tests/HealthChecks.Nats.Tests.csproj
    - name: Test
      run: dotnet test --no-restore --no-build ./test/HealthChecks.Nats.Tests/HealthChecks.Nats.Tests.csproj
