name: HealthChecks Solr CI

on:
  workflow_dispatch:
  push:
    branches: [ master, netcore-6.0 ]
    paths:
      - src/HealthChecks.Solr/**
      - test/HealthChecks.Solr.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_solr_ci.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
      - preview-*

  pull_request:
    branches: [ master ]
    paths:
      - src/HealthChecks.Solr/**
      - test/HealthChecks.Solr.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_solr_ci.
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    runs-on: ubuntu-latest
    # container: mcr.microsoft.com/dotnet/sdk:6.0
    # services:
    #   solr:
    #     image: solr:8.4.1
    #     ports:
    #       - 8983:8983
    #     volumes:
    #       - ${{ github.workspace }}/build/docker-services/solrcore:/var/solr/data/solrcore
    #       - ${{ github.workspace }}/build/docker-services/solrcoredown:/var/solr/data/solrcoredown
    steps:
      # - name: Provide permission for deleting volume files
      #   run: sudo chown -R $USER:$USER /home/runner/work/${{ github.event.repository.name }}

      - uses: actions/checkout@v3
      - name: Initialize Solr
        run: |
          docker run -d -p8983:8983 -v${{ github.workspace }}/build/docker-services/solrcore:/var/solr/data/solrcore -v${{ github.workspace }}/build/docker-services/solrcoredown:/var/solr/data/solrcoredown solr:8.4.1
      - name: Test Solr
        run: |
          wget http://localhost:8983/solr/#
          curl http://localhost:8983/solr/# -v
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            7.0.x
            8.0.x
      - name: Restore
        run: |
          dotnet restore ./src/HealthChecks.Solr/HealthChecks.Solr.csproj &&
          dotnet restore ./test/HealthChecks.Solr.Tests/HealthChecks.Solr.Tests.csproj
      - name: Check formatting
        run: |
          dotnet format --no-restore --verify-no-changes --severity warn ./src/HealthChecks.Solr/HealthChecks.Solr.csproj || (echo "Run 'dotnet format' to fix issues" && exit 1) &&
          dotnet format --no-restore --verify-no-changes --severity warn ./test/HealthChecks.Solr.Tests/HealthChecks.Solr.Tests.csproj || (echo "Run 'dotnet format' to fix issues" && exit 1)
      - name: Build
        run: |
          dotnet build --no-restore ./src/HealthChecks.Solr/HealthChecks.Solr.csproj &&
          dotnet build --no-restore ./test/HealthChecks.Solr.Tests/HealthChecks.Solr.Tests.csproj
      #- name: Test
      #  run: >
      #  dotnet test
      #  ./test/HealthChecks.Solr.Tests/HealthChecks.Solr.Tests.csproj
      #  --no-restore
      #  --no-build
      #  --collect "XPlat Code Coverage"
      #    --results-directory .coverage
      #    --
      #    DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
      #- name: Upload Coverage
      #  uses: codecov/codecov-action@v3
      #  with:
      #    flags: Solr
      #    directory: .coverage
