name: HealthChecks Milvus CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.Milvus/**
      - test/HealthChecks.Milvus.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_milvus_ci.yml
      - Directory.Build.props
      - Directory.Build.targets
      - Directory.Packages.props
    tags-ignore:
      - release-*
      - preview-*

  pull_request:
    branches: [ master ]
    paths:
      - src/HealthChecks.Milvus/**
      - test/HealthChecks.Milvus.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_milvus_ci.yml
      - Directory.Build.props
      - Directory.Build.targets
      - Directory.Packages.props

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v3
      - name: 'wget'      
        run: 'wget https://github.com/milvus-io/milvus/releases/download/v2.4.6/milvus-standalone-docker-compose.yml -O docker-compose.yml'      
      - name: 'compose'
        run: 'sudo docker compose up -d'		
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            7.0.x
            8.0.x
      - name: Restore
        run: |
          dotnet restore ./src/HealthChecks.Milvus/HealthChecks.Milvus.csproj &&          
          dotnet restore ./test/HealthChecks.Milvus.Tests/HealthChecks.Milvus.Tests.csproj
      - name: Check formatting
        run: |
          dotnet format --no-restore --verify-no-changes --severity warn ./src/HealthChecks.Milvus/HealthChecks.Milvus.csproj || (echo "Run 'dotnet format' to fix issues" && exit 1) &&
          dotnet format --no-restore --verify-no-changes --severity warn ./test/HealthChecks.Milvus.Tests/HealthChecks.Milvus.Tests.csproj || (echo "Run 'dotnet format' to fix issues" && exit 1)
      - name: Build
        run: |
          dotnet build --no-restore ./src/HealthChecks.Milvus/HealthChecks.Milvus.csproj &&
          dotnet build --no-restore ./test/HealthChecks.Milvus.Tests/HealthChecks.Milvus.Tests.csproj
      - name: Test
        run: >
          dotnet test
          ./test/HealthChecks.Milvus.Tests/HealthChecks.Milvus.Tests.csproj
          --no-restore
          --no-build
          --collect "XPlat Code Coverage"
          --results-directory .coverage
          --
          DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
      - name: Upload Coverage
        uses: codecov/codecov-action@v5
        with:
          flags: Milvus
          directory: .coverage
