name: HealthChecks UI CI

on:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.UI/**
      - src/HealthChecks.UI.*/**
      - test/HealthChecks.UI.Tests/**
      - .github/workflows/healthchecks_ui_ci.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
  pull_request:
    branches: [ master ]
    paths:
    - src/HealthChecks.UI/**
    - test/HealthChecks.UI.Tests/**
    - .github/workflows/healthchecks_ui_ci.yml
    - Directory.Build.props
    - Directory.Build.targets

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server
        ports:
          - 5433:1433
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: Password12!
      npgsql:
        image: postgres
        ports:
          - 8010:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Password12!
      mysql:
        image: mysql
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: Password12!
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: false
    - name: Restore dependencies UI
      run: dotnet restore ./src/HealthChecks.UI/HealthChecks.UI.csproj
    - name: Restore dependencies UI.Client
      run: dotnet restore ./src/HealthChecks.UI.Client/HealthChecks.UI.Client.csproj
    - name: Restore dependencies UI.Core
      run: dotnet restore ./src/HealthChecks.UI.Core/HealthChecks.UI.Core.csproj
    - name: Restore dependencies UI.InMemory.Storage
      run: dotnet restore ./src/HealthChecks.UI.InMemory.Storage/HealthChecks.UI.InMemory.Storage.csproj
    - name: Restore dependencies UI.MySql.Storage
      run: dotnet restore ./src/HealthChecks.UI.MySql.Storage/HealthChecks.UI.MySql.Storage.csproj
    - name: Restore dependencies UI.PostgreSQL.Storage
      run: dotnet restore ./src/HealthChecks.UI.PostgreSQL.Storage/HealthChecks.UI.PostgreSQL.Storage.csproj
    - name: Restore dependencies UI.SQLite.Storage
      run: dotnet restore ./src/HealthChecks.UI.SQLite.Storage/HealthChecks.UI.SQLite.Storage.csproj
    - name: Restore dependencies UI.SqlServer.Storage
      run: dotnet restore ./src/HealthChecks.UI.SqlServer.Storage/HealthChecks.UI.SqlServer.Storage.csproj
    - name: Restore dependencies UI.K8s.Operator
      run: dotnet restore ./src/HealthChecks.UI.K8s.Operator/HealthChecks.UI.K8s.Operator.csproj
    - name: Build UI
      run: dotnet build --no-restore ./src/HealthChecks.UI/HealthChecks.UI.csproj
    - name: Build UI.Client
      run: dotnet build --no-restore ./src/HealthChecks.UI.Client/HealthChecks.UI.Client.csproj
    - name: Build UI.Core
      run: dotnet build --no-restore ./src/HealthChecks.UI.Core/HealthChecks.UI.Core.csproj
    - name: Build UI.InMemory.Storage
      run: dotnet build --no-restore ./src/HealthChecks.UI.InMemory.Storage/HealthChecks.UI.InMemory.Storage.csproj
    - name: Build UI.MySql.Storage
      run: dotnet build --no-restore ./src/HealthChecks.UI.MySql.Storage/HealthChecks.UI.MySql.Storage.csproj
    - name: Build UI.PostgreSQL.Storage
      run: dotnet build --no-restore ./src/HealthChecks.UI.PostgreSQL.Storage/HealthChecks.UI.PostgreSQL.Storage.csproj
    - name: Build UI.SQLite.Storage
      run: dotnet build --no-restore ./src/HealthChecks.UI.SQLite.Storage/HealthChecks.UI.SQLite.Storage.csproj
    - name: Build UI.SqlServer.Storage
      run: dotnet build --no-restore ./src/HealthChecks.UI.SqlServer.Storage/HealthChecks.UI.SqlServer.Storage.csproj
    - name: Build UI.K8s.Operator
      run: dotnet build --no-restore ./src/HealthChecks.UI.K8s.Operator/HealthChecks.UI.K8s.Operator.csproj
    #- name: Test
    #  run: dotnet test ./test/HealthChecks.UI.Tests/HealthChecks.UI.Tests.csproj --verbosity normal
