name: HealthChecks Aws.S3 CI

on:
  push:
   branches: [ master ]
   paths:
    - src/HealthChecks.Aws.S3/**
    - test/HealthChecks.Aws.S3.Tests/**
    - .github/workflows/healthchecks_aws_s3_ci.yml
    - Directory.Build.props
    - Directory.Build.targets
   tags-ignore:
    - release-*

  pull_request:
    branches: [ master ]
    paths:
    - src/HealthChecks.Aws.S3/**
    - test/HealthChecks.Aws.S3.Tests/**
    - .github/workflows/healthchecks_aws_s3_ci.yml
    - Directory.Build.props
    - Directory.Build.targets
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        include-prerelease: false
    - name: Restore dependencies
      run: dotnet restore ./src/HealthChecks.Aws.S3/HealthChecks.Aws.S3.csproj
    - name: Check formatting
      working-directory: ./src/HealthChecks.Aws.S3
      run: |
        dotnet format --no-restore --verify-no-changes --severity warn || (echo "Run 'dotnet format' to fix issues" && exit 1)
    - name: Build
      run: dotnet build --no-restore ./src/HealthChecks.Aws.S3/HealthChecks.Aws.S3.csproj
    - name: Test
      run: dotnet test ./test/HealthChecks.Aws.S3.Tests/HealthChecks.Aws.S3.Tests.csproj --verbosity normal

