name: HealthChecks Gremlin CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.Gremlin/**
      - test/HealthChecks.Gremlin.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_gremlin_ci.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*
      - preview-*

  pull_request:
    branches: [ master ]
    paths:
      - src/HealthChecks.Gremlin/**
      - test/HealthChecks.Gremlin.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_gremlin_ci.yml
      - Directory.Build.props
      - Directory.Build.targets

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      gremlin:
        image: tinkerpop/gremlin-server
        ports:
          - 8182:8182
        env:
          VIRTUAL_HOST: gremlin.docker
          VIRTUAL_PORT: 8182
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            7.0.x
            8.0.x
      - name: Restore
        run: |
          dotnet restore ./src/HealthChecks.Gremlin/HealthChecks.Gremlin.csproj &&
          dotnet restore ./test/HealthChecks.Gremlin.Tests/HealthChecks.Gremlin.Tests.csproj
      - name: Check formatting
        run: |
          dotnet format --no-restore --verify-no-changes --severity warn ./src/HealthChecks.Gremlin/HealthChecks.Gremlin.csproj || (echo "Run 'dotnet format' to fix issues" && exit 1) &&
          dotnet format --no-restore --verify-no-changes --severity warn ./test/HealthChecks.Gremlin.Tests/HealthChecks.Gremlin.Tests.csproj || (echo "Run 'dotnet format' to fix issues" && exit 1)
      - name: Build
        run: |
          dotnet build --no-restore ./src/HealthChecks.Gremlin/HealthChecks.Gremlin.csproj &&
          dotnet build --no-restore ./test/HealthChecks.Gremlin.Tests/HealthChecks.Gremlin.Tests.csproj
      - name: Test
        run: >
          dotnet test
          ./test/HealthChecks.Gremlin.Tests/HealthChecks.Gremlin.Tests.csproj
          --no-restore
          --no-build
          --collect "XPlat Code Coverage"
          --results-directory .coverage
          --
          DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          flags: Gremlin
          directory: .coverage
