name: HealthChecks Aws Systems Manager CD

on:
  push:
    tags:
      - release-aws_systemsmanager-*
      - release-all-*

jobs:
  build:
    env:
      BUILD_CONFIG: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x
      - name: Restore
        run: dotnet restore ./src/HealthChecks.Aws.SystemsManager/HealthChecks.Aws.SystemsManager.csproj
      - name: Build
        run: dotnet build --no-restore ./src/HealthChecks.Aws.SystemsManager/HealthChecks.Aws.SystemsManager.csproj -c $BUILD_CONFIG
      - name: Pack
        run: dotnet pack --no-build ./src/HealthChecks.Aws.SystemsManager/HealthChecks.Aws.SystemsManager.csproj -c $BUILD_CONFIG -o ./artifacts
      - name: Publish
        run: dotnet nuget push ./artifacts/AspNetCore.HealthChecks.Aws.SystemsManager.*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
